services:
  - type: web
    name: vesit-smart-events
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: vesit_acc_super_secret_jwt_key_2026
