apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: college-events
    tier: database
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
  mysql-database: "college_events"
  jwt-secret: "vesit_acc_super_secret_jwt_key_2026"
